import SLOT from '@/components/SLOT.vue'
import CT_MENU_MAIN from '@/components/CT_MENU_MAIN.vue'
import CT_HALF_IMAGE_HALF_TEXT from '@/components/CT_HALF_IMAGE_HALF_TEXT.vue'
import CT_ONE_THIRD_IMAGE_TWO_THIRD_TEXT from '@/components/CT_ONE_THIRD_IMAGE_TWO_THIRD_TEXT.vue'
import CT_TWO_THIRD_IMAGE_ONE_THIRD_TEXT from '@/components/CT_TWO_THIRD_IMAGE_ONE_THIRD_TEXT.vue'
import CT_FULL_TEXT from '@/components/CT_FULL_TEXT.vue'
import CT_SLIDER_THUMBNAIL from '@/components/CT_SLIDER_THUMBNAIL.vue'
import CT_CREATE_USER_ACCOUNT from '@/components/CT_CREATE_USER_ACCOUNT.vue'
import CT_USER_ACTIVATE_ACCOUNT from '@/components/CT_USER_ACTIVATE_ACCOUNT.vue'
import CT_USER_LOGIN from '@/components/CT_USER_LOGIN.vue'
import CT_USER_LOGOUT from '@/components/CT_USER_LOGOUT.vue'
import CT_USER_PASSWORD_FORGET from '@/components/CT_USER_PASSWORD_FORGET.vue'
import CT_USER_PROFILE_WIDGET from '@/components/CT_USER_PROFILE_WIDGET.vue'
import CT_MENU_SIDE from '@/components/CT_MENU_SIDE.vue'
import CT_MENU_CATEGORY from '@/components/CT_MENU_CATEGORY.vue'
import CT_USER_PASSWORD_MODIFY from '@/components/CT_USER_PASSWORD_MODIFY.vue'
import CT_USER_ACCOUNT_MODIFY from '@/components/CT_USER_ACCOUNT_MODIFY.vue'
import CT_SPACER from '@/components/CT_SPACER.vue'
import CT_DISPLAY_JUMBO from '@/components/CT_DISPLAY_JUMBO.vue'
import CT_DISPLAY_SMALL from '@/components/CT_DISPLAY_SMALL.vue'
import CT_DISPLAY_MEDIUM from '@/components/CT_DISPLAY_MEDIUM.vue'
import CT_DISPLAY_THREE from '@/components/CT_DISPLAY_THREE.vue'
import CT_IMAGE from '@/components/CT_IMAGE.vue'
import CT_CATEGORY_INFO from '@/components/CT_CATEGORY_INFO.vue'


export default {
    'rf-slot':SLOT,
    'CT_MENU_MAIN': CT_MENU_MAIN,
    'CT_HALF_IMAGE_HALF_TEXT': CT_HALF_IMAGE_HALF_TEXT,
    'CT_ONE_THIRD_IMAGE_TWO_THIRD_TEXT': CT_ONE_THIRD_IMAGE_TWO_THIRD_TEXT,
    'CT_TWO_THIRD_IMAGE_ONE_THIRD_TEXT': CT_TWO_THIRD_IMAGE_ONE_THIRD_TEXT,
    'CT_FULL_TEXT': CT_FULL_TEXT,
    'CT_SLIDER_THUMBNAIL': CT_SLIDER_THUMBNAIL,
    'CT_CREATE_USER_ACCOUNT': CT_CREATE_USER_ACCOUNT,
    'CT_USER_ACTIVATE_ACCOUNT': CT_USER_ACTIVATE_ACCOUNT,
    'CT_USER_LOGIN': CT_USER_LOGIN,
    'CT_USER_LOGOUT': CT_USER_LOGOUT,
    'CT_USER_PASSWORD_FORGET': CT_USER_PASSWORD_FORGET,
    'CT_USER_PROFILE_WIDGET': CT_USER_PROFILE_WIDGET,
    'CT_MENU_CATEGORY': CT_MENU_CATEGORY,
    'CT_MENU_SIDE': CT_MENU_SIDE,
    'CT_USER_PASSWORD_MODIFY': CT_USER_PASSWORD_MODIFY,
    'CT_USER_ACCOUNT_MODIFY':CT_USER_ACCOUNT_MODIFY,
    'CT_SPACER': CT_SPACER,
    'CT_DISPLAY_JUMBO': CT_DISPLAY_JUMBO,
    'CT_DISPLAY_SMALL': CT_DISPLAY_SMALL,
    'CT_DISPLAY_MEDIUM': CT_DISPLAY_MEDIUM,
    'CT_DISPLAY_THREE': CT_DISPLAY_THREE,
    'CT_IMAGE': CT_IMAGE,
    'CT_CATEGORY_INFO': CT_CATEGORY_INFO
}