import SLOT from '@/components/SLOT.vue'
import CT_MENU_MAIN from '@/components/CT_MENU_MAIN.vue'
import CT_HALF_IMAGE_HALF_TEXT from '@/components/CT_HALF_IMAGE_HALF_TEXT.vue'
import CT_ONE_THIRD_IMAGE_TWO_THIRD_TEXT from '@/components/CT_ONE_THIRD_IMAGE_TWO_THIRD_TEXT.vue'
import CT_FULL_TEXT from '@/components/CT_FULL_TEXT.vue'
import CT_SLIDER_THUMBNAIL from '@/components/CT_SLIDER_THUMBNAIL.vue'
import CT_CREATE_USER_ACCOUNT from '@/components/CT_CREATE_USER_ACCOUNT.vue'
import CT_USER_ACTIVATE_ACCOUNT from '@/components/CT_USER_ACTIVATE_ACCOUNT.vue'
import CT_USER_LOGIN from '@/components/CT_USER_LOGIN.vue'
import CT_USER_LOGOUT from '@/components/CT_USER_LOGOUT.vue'
import CT_USER_PASSWORD_FORGET from '@/components/CT_USER_PASSWORD_FORGET.vue'

export default {
    'rf-slot':SLOT,
    'CT_MENU_MAIN': CT_MENU_MAIN,
    'CT_HALF_IMAGE_HALF_TEXT': CT_HALF_IMAGE_HALF_TEXT,
    'CT_ONE_THIRD_IMAGE_TWO_THIRD_TEXT': CT_ONE_THIRD_IMAGE_TWO_THIRD_TEXT,
    'CT_FULL_TEXT': CT_FULL_TEXT,
    'CT_SLIDER_THUMBNAIL': CT_SLIDER_THUMBNAIL,
    'CT_CREATE_USER_ACCOUNT': CT_CREATE_USER_ACCOUNT,
    'CT_USER_ACTIVATE_ACCOUNT': CT_USER_ACTIVATE_ACCOUNT,
    'CT_USER_LOGIN': CT_USER_LOGIN,
    'CT_USER_LOGOUT': CT_USER_LOGOUT,
    'CT_USER_PASSWORD_FORGET': CT_USER_PASSWORD_FORGET
}